apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-decision-deployment
  labels:
    app: decision
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
spec:
  replicas: 3
  selector:
    matchLabels:
      app: decision
  template:
    metadata:
      labels:
        app: decision
    spec:
      containers:
      - name: appdecision
        image: ggrab/appdecision:0.0.10
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-decision-service
  labels:
    app: decision
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: decision
