name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: development

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Test the Docker Image
      run: cd app-decision && docker build --target tester . --file Dockerfile --tag ggrab/appdecision:test
    - name: Publish the Docker Image
      run: |
        DATE=$(date +%s)
        cd app-decision
        docker build . --file Dockerfile --tag ggrab/appdecision:latest
        docker tag ggrab/appdecision:latest ggrab/appdecision:$DATE
        docker push ggrab/appdecision:latest
        docker push ggrab/appdecision:$DATE
